services:
  graalvm-builder:
    image: ubuntu:22.04
    container_name: graalvm-builder
    tty: true
    stdin_open: true
    volumes:
      - ./demo:/home/builder/project
      - ./setup-graalvm-native-full.sh:/home/builder/setup-graalvm-native-full.sh
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/builder
    command: [ "/bin/bash" ]
