apiVersion: v1
kind: Service
metadata:
  name: pais-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: pais-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pais-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pais-service
  template:
    metadata:
      labels:
        app: pais-service
    spec:
      containers:
        - name: pais
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
