apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-volumen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-volumen
  template:
    metadata:
      labels:
        app: webapp-volumen
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "256Mi"
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config