apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "256Mi"
        env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: GREETING
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080